### ISSUE TITLE
BUG : Cannot send message

### ISSUE THREAD

**Issue by PiloteCode** [Z0rdak/Yet-Another-World-Protector#88]
Hi, when I try to send a message on my server

[21:39:59 INFO]: cli.msg.dim.info.player.added [cli.link.action.undo.text]
[21:40:04 ERROR]: Exception caught during firing event: net/minecraftforge/event/ServerChatEvent
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: class de.z0rdak.yawp.handler.flags.PlayerFlagHandler onSendChat(Lnet/minecraftforge/event/ServerChatEvent;)V
java.lang.NoClassDefFoundError: net/minecraftforge/event/ServerChatEvent
        at de.z0rdak.yawp.handler.flags.__PlayerFlagHandler_onSendChat_ServerChatEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@43.2.14/net.minecraftforge.common.ForgeHooks.onServerChatSubmittedEvent(ForgeHooks.java:460)
        at TRANSFORMER/forge@43.2.14/net.minecraftforge.common.ForgeHooks$1.lambda$decorate$0(ForgeHooks.java:473)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.ServerChatEvent
        ... 13 more
[21:40:04 ERROR]: Chain link failed, continuing to next one
java.lang.NoClassDefFoundError: net/minecraftforge/event/ServerChatEvent
        at de.z0rdak.yawp.handler.flags.__PlayerFlagHandler_onSendChat_ServerChatEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar:?] {}
        at net.minecraftforge.common.ForgeHooks.onServerChatSubmittedEvent(ForgeHooks.java:460) ~[?:?] {re:classloading}
        at net.minecraftforge.common.ForgeHooks$1.lambda$decorate$0(ForgeHooks.java:473) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.ServerChatEvent
        ... 13 more

**Comment by PiloteCode** [comment]
On 1.19.2 mohist

**Comment by Z0rdak** [comment]
Thank you for adding more information about your mod loader. Unfortunately, I do not support hybrid servers.

Since this works fine on a pure forge server, it seems reasonable to assume that this has something todo with Mohist's side. 

> `java.lang.NoClassDefFoundError: net/minecraftforge/event/ServerChatEvent` 

Please contact them.

Best regards
